// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLv0NdWhnPWHZW0613SpmOBSfbDepSCVQ',
    appId: '1:510363129448:web:fd203d7dad26b4babb4ddd',
    messagingSenderId: '510363129448',
    projectId: 'examenpspcarlosescriva',
    authDomain: 'examenpspcarlosescriva.firebaseapp.com',
    storageBucket: 'examenpspcarlosescriva.appspot.com',
    measurementId: 'G-B99SM1ZBM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkyzlpDldyliRxRK2z6XzXfBsAmZOTDsM',
    appId: '1:510363129448:android:6a9ed3838c765b02bb4ddd',
    messagingSenderId: '510363129448',
    projectId: 'examenpspcarlosescriva',
    storageBucket: 'examenpspcarlosescriva.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq3P6wuJB6IU0hYSiH8Bo6GaV0VAV4wYw',
    appId: '1:510363129448:ios:50b55b644653d0d3bb4ddd',
    messagingSenderId: '510363129448',
    projectId: 'examenpspcarlosescriva',
    storageBucket: 'examenpspcarlosescriva.appspot.com',
    iosBundleId: 'com.example.carlosescrivaExamepsp',
  );
}
